### ISSUE TITLE
Incorrect formatted log output

### ISSUE THREAD

**Issue by tboerger** [drone-plugins/drone-s3-cache#10]
Currently we are getting a wrong formatted line within the log output:

```
time="2017-08-07T14:47:01Z" level=info msg="Flushing cache items older then %!s(int=14) days at /foo/bar/master/archive.tar" 
```

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
https://github.com/drone-plugins/drone-s3-cache/blob/master/plugin.go#L68

It already has been fixed. right?

**Comment by tboerger** [comment]
True, already solved via https://github.com/drone-plugins/drone-s3-cache/commit/ac77c5a86828457de74eb74809989e464e949b6a
