### ISSUE TITLE
Usage for me

### ISSUE THREAD

**Issue by ozbillwang** [drone-plugins/drone-s3-cache#12]
I have the request to cache to s3, and try to understand this plugin, but not sure how to use it in pipeline. 

Can I have the detail usage and instruction as other cache plugins, such as:

http://plugins.drone.io/drillster/drone-volume-cache/

http://plugins.drone.io/appleboy/drone-sftp-cache/

By the way, if this plugin works, can we include it in http://plugins.drone.io ?

**Comment by appleboy** [comment]
@ozbillwang See http://plugins.drone.io/drone-plugins/drone-s3/

**Comment by appleboy** [comment]
@ozbillwang I will take it.

**Comment by tboerger** [comment]
It is documented, just not pushed to the plugin index: https://github.com/drone-plugins/drone-s3-cache/blob/master/DOCS.md

**Comment by ozbillwang** [comment]
Thanks, @tboerger Can we merge this document into `README.md`?

**Comment by appleboy** [comment]
@ozbillwang see #13

**Comment by tboerger** [comment]
This document should be added to the plugin index instead

**Comment by ozbillwang** [comment]
Thanks @appleboy. But I still prefer to copy `DOCS.md` directly into `README.md`, more than a link.

**Comment by tboerger** [comment]
That won't happen, all plugins will have the readme on the plugin index and just a link to it within the readme

**Comment by ozbillwang** [comment]
Thanks for the explanation @tboerger
