### ISSUE TITLE
Documentation doesn't exist

### ISSUE THREAD

**Issue by tonglil** [drone-plugins/drone-s3-cache#21]
The link to the docs is broken, and there doesn't actually seem to be documentation for this plugin.

**Comment by tboerger** [comment]
This will be resolved if https://github.com/drone/drone-plugin-index/pull/50 gets merged

**Comment by tboerger** [comment]
Oh, wrong... It's already documented at https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-s3-cache/index.md

**Comment by tonglil** [comment]
@tboerger for some reason it's not showing up on http://plugins.drone.io/

**Comment by tboerger** [comment]
@tonglil https://beta.drone.io/drone/drone-plugin-index shows that your link to the docker plugin has broken the build, so it's clear that we don't get updates :)
