### ISSUE TITLE
Support different bucket name conventions

### ISSUE THREAD

**Issue by jbrockopp** [drone-plugins/drone-s3-cache#33]
We have a use-case where an end-user has an org on GitHub that has less than 3 characters. 

From [Amazon](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html):

> Bucket names must be at least 3 and no more than 63 characters long

Now I'll admit that it took us over 2 years to run into this issue so I understand the initial grimace at implementing this. However, since it is allowed by VC systems (like GitHub and GitLab), I believe an argument could be made that it's a bug since it's functionality supported by the VCS but breaks because of the plugin.

**Comment by jbrockopp** [comment]
We came up with a few initial ideas and we wondering if one was more favorable than the other:

1. Make the plugin by default append `drone-` before every bucket name
  * This would be the easiest implementation
  * Would prevent end-users from having an org name that is > 57 characters
2. Serialize the org name (base64, md5, sha)
  * Guarantee to not have bucket name conflicts
  * Knowing who owns what bucket becomes more challenging
3. Allow the end-user to override the bucket name
  * Easy to implement
  * Could cause bucket name conflicts if a end-user chooses a bucket name that is the same as another org name
4. Allow the end-user to append a prefix/suffix
  * Easy to implement
  * Could cause bucket name conflicts if a end-user appends a prefix/suffix to their org that causes their bucket name to be the same as another org name

Thoughts on the above?

**Comment by tboerger** [comment]
You can already customize all paths via attributes, to be more specific you can overwrite `root` and also `path`. They are also more or less documented at http://plugins.drone.io/drone-plugins/drone-s3-cache/#parameter-reference.

The element you want to change should be specifically `root` to change the used bucket, for reference:

* https://github.com/drone-plugins/drone-s3-cache/blob/master/main.go#L312
* https://github.com/drone-plugins/drone-s3-cache/blob/master/main.go#L179-L190

So IMHO we don't need to change anything on this plugin itself, maybe we should simply provide an example on the documentation that explains the behavior of `root` and `path` properly.

**Comment by jbrockopp** [comment]
@tboerger I didn't even know that was possible. I think just adding some example docs would be plenty sufficient then!

**Comment by tboerger** [comment]
Maybe you want to create an pull request to the plugin index? :)

Or raise an issue over there...

**Comment by jbrockopp** [comment]
Sure I'll do so. Thanks again! 👍
