### ISSUE TITLE
Support for Multipart Upload/Download

### ISSUE THREAD

**Issue by jmccann** [drone-plugins/drone-s3-cache#35]
Seems on files greater then certain sizes a Multipart Upload/Download can be more performant.   (15MB is when upload manager uses it)

Seems there are upload/download managers available to take advantage of this feature easily.  It'll determine the *when* and handle it automatically.

**References**
* https://docs.aws.amazon.com/sdk-for-go/api/service/s3/
* https://docs.aws.amazon.com/AmazonS3/latest/dev/usingHLmpuPHP.html

**Comment by donny-dont** [comment]
@jmccann the s3 cache actually uses minio-go. I thought it did the multipart but I'm not completely sure.

**Comment by jmccann** [comment]
OK, I'll look into it

**Comment by jmccann** [comment]
So, from minio-go master it does seem there is logic for multipart uploading 😄 

https://github.com/minio/minio-go/blob/6f8ee6677a042d53d9251ecf7b1c7431c23d2416/api-put-object.go#L138-L165

**Comment by donny-dont** [comment]
Ok so were already using it then 🎊
