### ISSUE TITLE
Support S3 transfer acceleration

### ISSUE THREAD

**Issue by mithrandi** [drone-plugins/drone-s3-cache#37]
S3 transfer acceleration requires this: https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html#transfer-acceleration-getting-started

When trying to use this:

```
time="2018-07-07T13:57:54Z" level=info msg="Restoring cache at /fusionapp/fusion/master/archive.tar"
time="2018-07-07T13:57:54Z" level=info msg="Retrieving file in fusionapp at fusion/master/archive.tar"
time="2018-07-07T13:57:57Z" level=warning msg="Cache could not be restored The specified bucket does not exist."
```

I believe this is because it expects the first path component to be the bucket name.

**Comment by mithrandi** [comment]
There's a member in Options that seems like it might work, but maybe it does nothing?

https://github.com/drone-plugins/drone-s3-cache/blob/f480bb823beb2b73ee8310d36f4db85756f2fdac/storage/s3/s3.go#L36

**Comment by mithrandi** [comment]
Looks like `minio.BucketLookupDNS` is what's needed on the Minio side.

**Comment by tboerger** [comment]
Pathstyle is an option required for Minio access because Minio is working with paths per bucket and not subdomains per bucket.

**Comment by tboerger** [comment]
For reference: https://docs.minio.io/docs/golang-client-api-reference#SetS3TransferAccelerate

**Comment by mithrandi** [comment]
That call is about turning on acceleration, so I think not directly related here.

**Comment by tboerger** [comment]
That call is about setting the accelerated endpoint, and this seems to be exactly the option required to integrate support for it.

**Comment by mithrandi** [comment]
Whoops, you're right, I completely misread the docs!

**Comment by mithrandi** [comment]
I changed the title to be more specific in light of the above.
