### ISSUE TITLE
Regression in c1c22f16fcd210ceda5a961da008dfedee63cf56

### ISSUE THREAD

**Issue by mithrandi** [drone-plugins/drone-s3-cache#41]
After c1c22f16fcd210ceda5a961da008dfedee63cf56 all my cache ops are failing with:

```time="2018-07-10T22:10:26Z" level=warning msg="Cache could not be restored The provided token is malformed or otherwise invalid."```

**Comment by donny-dont** [comment]
@mithrandi can you try setting the region to be an empty string?

**Comment by mithrandi** [comment]
Yup, that fixes it. Presumably because my bucket has no location constraint?

**Comment by donny-dont** [comment]
I'm guessing so.
