### ISSUE TITLE
Support Getting Credentials From Credentials File

### ISSUE THREAD

**Issue by kirbyjs** [drone-plugins/drone-s3-cache#62]
### Description

It would be awesome if you guys would support getting creds with [NewFileAWSCredentials](https://godoc.org/github.com/minio/minio-go/pkg/credentials#NewFileAWSCredentials), [where you are fetching credentials](https://github.com/drone-plugins/drone-s3-cache/blob/master/storage/s3/s3.go#L45:L55). Seems like you could also use the [NewChainCredentials](https://godoc.org/github.com/minio/minio-go/pkg/credentials#NewChainCredentials), to simplify the logic and just pass your credentials providers to the chain, and then the chain will try to resolve getting creds from any of the providers that you specified.

#### Expected
This plugin should be able to load and use credentials from `~/.aws/credentials`.

#### Actual
Currently getting the error `Access Denied` when using this plugin when aws credentials are in the shared credentials file. 

#### Context
- https://discourse.drone.io/t/amazon-s3-cache-plugin-with-aws-credentials-file/7901

**Comment by donny-dont** [comment]
@kirbyjs can you give some more information here on what would be passed into `NewFileAWSCredentials`? What additional values would the config need? PRs are definitely welcome if you'd like.
