### ISSUE TITLE
tar.gz compression

### ISSUE THREAD

**Issue by decaz** [drone-plugins/drone-s3-cache#68]
Currently just https://github.com/drone/drone-cache-lib/tree/master/archive/tar is in use.

I see https://github.com/drone/drone-cache-lib/blob/master/archive/tgz exists but there is no option to enable tar.gz compression. It would be nice to have an option to turn it on.

**Comment by raulsh** [comment]
"filename" paramater can be filled with a filename ending with "tar.gz" and after that the file will be compressed with tgz

**Comment by decaz** [comment]
@raulsh thank you!
